# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rich Werden
description: "A simple site for Rich Werden to write about code and archive some completed projects for future reference..." # 'Code Conquerer'
url: 'https://github.com/r-i-c-h/r-i-c-h.github.io' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Rich Werden'
  email: rich_@t_richwerden.com
  twitter_username: the_riz
  github_username:  r-i-c-h
  linkedin_username:  r-i-c-h

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
sass:
    sass_dir: _sass
    style: compressed

# kramdown:
#   # use Github Flavored Markdown
#   input: GFM
#   # do not replace newlines by <br>s
#   hard_wrap: false

plugins:
  - jekyll-paginate